---
title: "Data"
author: "Katherine Wang"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = F, include = T)

library(readr)
library(tidyverse)
library(janitor)
library(ggplot2)
library(tidycensus)
library(readxl)
library(janitor)
library(ggmap)
library(maps)
library(mapdata)
library(viridis)
library(gganimate)
library(gifski)
# devtools::install_github('thomasp85/gganimate')
library(extrafont)
library(data.table)
library(sf)
library(here)
library(tis)
```


```{r cleanData}

# I created these three lists -- datapoints, datapoints1, and us_states -- to
# help me select the variables I need from the tables as well as organize my
# tables later on so that the states' names will be retained.

datapoints <- c("geo_name", "se_a12003a_001", "se_a12003a_002", "se_a12003a_003", "se_a12003b_001", "se_a12003b_002", "se_a12003b_003", "se_a14009_001", "se_a14009_002", "se_a14009_003", "se_a14009_004", "se_a14009_005", "se_a14009_006", "se_a14009_009", "se_a14009_010")

datapoints1 <- c("se_a12003a_001", "se_a12003a_002", "se_a12003a_003", "se_a12003b_001", "se_a12003b_002", "se_a12003b_003", "se_a14009_001", "se_a14009_002", "se_a14009_003", "se_a14009_004", "se_a14009_005", "se_a14009_006", "se_a14009_009", "se_a14009_010")

us_states <- c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming", "Puerto Rico")

datapoints2 <- c("geo_name", "se_a13001a_001", "se_a13001a_002", "se_a13001b_001", "se_a13001b_002", "se_a13001d_001", "se_a13001d_002", "se_a13001h_001", "se_a13001h_002", "se_a13005_001", "se_a13005_003", "se_a13005_004")

datapoints3 <- c("geo_name", "se_a17005a_001", "se_a17005a_003", "se_a17005b_001", "se_a17005b_003", "se_a17006a_001", "se_a17006a_003", "se_a17006b_001", "se_a17006b_003", "se_a17006d_001", "se_a17006d_003", "se_a17006h_001", "se_a17006h_003")

datapoints4 <- c("geo_name", "se_a12003a_001", "se_a12003a_002", "se_a12003b_001", "se_a12003b_002", "se_a17005a_001", "se_a17005a_003", "se_a17005b_001", "se_a17005b_003", "se_a17006a_001", "se_a17006a_003", "se_a17006b_001", "se_a17006b_003", "se_a17006d_001", "se_a17006d_003", "se_a17006h_001", "se_a17006h_003")

# I downloaded the ACS file, transformed all the columns into character values
# so that it could be loaded into a table, and skipped the first line so that
# the first row of the tables shows the variable names. I cleaned the names in
# order to facilitate calling variables later on, and I selected certain
# variables to display, which were collectively under the list called
# datapoints.

acs2017 <- read_csv("raw-data/R12497278_SL040.csv", 
                    col_types = cols(.default = col_character()), 
                    skip = 1) %>% 
  clean_names() %>% 
  select(all_of(datapoints))

# In order to convert the columns from characters into numeric values, I used
# the as.numeric function on the entire tibble. However, this rendered the first
# column, which showed the names of the states, into NAs. Thus, I first pulled
# out the state names column, changed the rest of the tibble into numeric
# values, created a new list of all the states names, and then joined that list
# with the numeric tibble to get a table that has state names as characters and
# all the numbers as numeric values.

acs_states <- acs2017[1]
acs2017[] <- lapply(acs2017, function(x) as.numeric(as.character(x)))
acs_a <- acs2017 %>% select(datapoints1) %>% mutate(geo_name = us_states)
acs <- inner_join(acs_states, acs_a, by = "geo_name")

# I also loaded the NCES data, skipped the first five lines so that the variable
# names are in the first row, and selected the variables I needed. I omitted all
# the NAs to make the data more readable.

nces2017 <- read_xls("raw-data/tabn219.46.xls", skip = 5) %>% 
  select("1", "9", "10", "11", "12") %>% 
  na.omit()

pov_status <- read_csv("raw-data/R12518258_SL040.csv") %>% 
  clean_names() %>% 
  select(all_of(datapoints2))

pov_status$geo_name <- tolower(pov_status$geo_name)

unemp_data <- read_csv("raw-data/R12529099_SL040.csv") %>% 
  clean_names() %>% 
  select(all_of(datapoints3))

county_data <- read_csv("raw-data/R12536075_SL050.csv") %>% 
  clean_names() %>% 
  select(all_of(datapoints4)) %>% 
  mutate(subregion = sapply(strsplit(county_data$geo_name, " County"), "[", 1)) %>% 
  mutate(region = sapply(strsplit(county_data$geo_name, ", "), "[", -1))
county_data$subregion <- tolower(county_data$subregion)
county_data$region <- tolower(county_data$region)
```


```{r dropout_sex}

#dropout based on sex
dropout_county_male <- county_data %>% 
  select(region, subregion, se_a12003a_001, se_a12003a_002) %>% 
  mutate(drop_rate = (se_a12003a_002/se_a12003a_001)*100) %>% 
  mutate(type = "male") %>% 
  select(region, subregion, drop_rate, type)

dropout_county_female <- county_data %>% 
  select(region, subregion, se_a12003b_001, se_a12003b_002) %>% 
  mutate(drop_rate = (se_a12003b_002/se_a12003b_001)*100) %>% 
  mutate(type = "female") %>% 
  select(region, subregion, drop_rate, type)

dropout_county_both <- rbind(dropout_county_male, dropout_county_female)
dropout_county <- full_join(county, dropout_county_both, by = c("region", "subregion")) %>% 
  na.omit()

dropout_county %>% filter(region == input$state) %>% 
                ggplot(aes(x = long, y = lat, group = group, fill = drop_rate)) +
                geom_polygon(color = "white") +
                facet_wrap(~ type) +
                labs(title = "School Dropout Rate for 16-19 Year Old Students \n By Sex in 2017",
                     subtitle = "New York County Level Data",
                     caption = "Source: American Community Survey 2017",
                     fill = "Dropout Rate") +
                scale_fill_viridis(option = "magma", 
                                   direction = -1,
                                   guide = guide_colorbar(direction = "horizontal",
                                                          barheight = unit(2, units = "mm"),
                                                          barwidth = unit(35, units = "mm"),
                                                          draw.ulim = FALSE,
                                                          title.position = "top",
                                                          title.hjust = 0.5,
                                                          label.hjust = 0.5)) +
                theme(legend.position = "bottom",
                      legend.spacing.x = unit(1, 'cm')) +
                theme_void()
```


```{r unemp_sex}
#combine all
 dropout_county_male <- county_data %>% 
            select(region, subregion, se_a12003a_001, se_a12003a_002) %>% 
            mutate(data = (se_a12003a_002/se_a12003a_001)*100) %>% 
            mutate(type = "male") %>% 
            mutate(datatype = "Dropout Rate") %>% 
            select(region, subregion, data, type, datatype)
        
        dropout_county_female <- county_data %>% 
            select(region, subregion, se_a12003b_001, se_a12003b_002) %>% 
            mutate(data = (se_a12003b_002/se_a12003b_001)*100) %>% 
            mutate(type = "female") %>% 
            mutate(datatype = "Dropout Rate") %>% 
            select(region, subregion, data, type, datatype)
        
        dropout_county_both <- rbind(dropout_county_male, dropout_county_female)
        
        unemp_county_male <- county_data %>% 
            select(region, subregion, se_a17005a_001, se_a17005a_003) %>% 
            mutate(data = (se_a17005a_003/se_a17005a_001)*100) %>% 
            mutate(type = "male") %>% 
            mutate(datatype = "Unemployment Rate") %>% 
            select(region, subregion, data, type, datatype)
        
        unemp_county_female <- county_data %>% 
            select(region, subregion, se_a17005b_001, se_a17005b_003) %>% 
            mutate(data = (se_a17005b_003/se_a17005b_001)*100) %>% 
            mutate(type = "female") %>% 
            mutate(datatype = "Unemployment Rate") %>% 
            select(region, subregion, data, type, datatype)

unemp_county_both <- rbind(unemp_county_male, unemp_county_female)
county_all <- rbind(unemp_county_both, dropout_county_both)
county_all_final <- left_join(county, county_all, by = c("region", "subregion"))

        county_all_final$type <- toupper(county_all_final$type)
        county_all_final$region <- toupper(county_all_final$region)
        
        
county_all_final %>% 
  filter(region == "ALABAMA") %>%
  filter(datatype == "Dropout Rate") %>% 
  ggplot(aes(x = long, y = lat, group = group, fill = data)) +
  geom_polygon(color = "white") +
  facet_wrap(~ type) +
  labs(title = "Unemployment Rate for Civilians 16+ Years in Labor Force \n By Sex in 2017",
       subtitle = "New York County Level Data",
       caption = "Source: American Community Survey 2017",
       fill = "Unemployment Rate") +
  scale_fill_viridis(option = "viridis", 
                     direction = -1,
                     guide = guide_colorbar(direction = "horizontal",
                                            barheight = unit(2, units = "mm"),
                                            barwidth = unit(35, units = "mm"),
                                            draw.ulim = FALSE,
                                            title.position = "top",
                                            title.hjust = 0.5,
                                            label.hjust = 0.5)) +
   theme(legend.position = "bottom",
        legend.spacing.x = unit(1, 'cm')) +
  theme_void()
```


```{r states}

# I downloaded data for the states and counties, which is already stored in R. 
states <- map_data("state")
county <- map_data("county")
```


```{r dropout_sex}

# My first task was to create a map displaying school graduation rates for the
# male population. I filtered the ACS data, selecting the three variables I
# needed, and created a new variable, drop_rate, to help me measure the percent
# of those who droppoued out I created another variable, type, to remind me that
# this was for the male population, just in case I choose to combine the female
# and male datasets later on. I renamed some variables into names that held
# meaning for the user.

male <- acs %>% 
  select(geo_name, 
         se_a12003a_001, 
         se_a12003a_002) %>% 
  mutate(drop_rate = (se_a12003a_002/se_a12003a_001)*100) %>% 
  mutate(type = "male") %>% 
  mutate(total = se_a12003a_001, drop = se_a12003a_002) %>% 
  mutate(region = geo_name)

# I then turned all the states in the geo_name column into lowercase letters so
# that it would facilitate the left_join function that I would later use.
male$region <- tolower(male$geo_name)

# I creatd a new male graduation rate tibble that only selected the variables I
# needed.
male_new <- male %>% 
  select(region, total, drop, drop_rate, type)

# I copied what I did for the male graduation rate table, applying it to the
# female graduation rate. My first task was to create a map displaying school
# graduation rates for the female population. I filtered the ACS data, selecting
# the three variables I needed, and created a new variable, grad_rate, to help
# me measure the percent of those who graduated. I created another variable,
# type, to remind me that this was for the female population, just in case I
# choose to combine the female and male datasets later on. I renamed some
# variables into names that held meaning for the user.

female <- acs %>% 
  select(geo_name, 
         se_a12003b_001, 
         se_a12003b_002) %>% 
  mutate(drop_rate = (se_a12003b_002/se_a12003b_001)*100) %>% 
  mutate(type = "female") %>% 
  mutate(total = se_a12003b_001, drop = se_a12003b_002) %>% 
  mutate(region = geo_name)
female$region <- tolower(female$geo_name)
female_new <- female %>% 
  select(region, total, drop, drop_rate, type)

# I first combined the female and male graduation rates tables into a new tibble
# called "both." Then I joined "both" with the states data to get "combo."
both <- rbind(female_new, male_new)
combo <- left_join(states, both, by = "region") %>% 
  select(long, lat, order, group, region, drop_rate, type)
```


```{r sex_unemp}

# for males
male1 <- unemp_data %>% 
  select(geo_name, 
         se_a17005a_001, 
         se_a17005a_003) %>% 
  mutate(unemp = (se_a17005a_003/se_a17005a_001)*100) %>% 
  mutate(type = "male") %>% 
  mutate(region = geo_name)

# I then turned all the states in the geo_name column into lowercase letters so
# that it would facilitate the left_join function that I would later use.

male1$region <- tolower(male1$geo_name)
male1 <- male1 %>% 
  select(region, unemp, type)

# for females
female1 <- unemp_data %>% 
  select(geo_name, 
         se_a17005b_001, 
         se_a17005b_003) %>% 
  mutate(unemp = (se_a17005b_003/se_a17005b_001)*100) %>% 
  mutate(type = "female") %>% 
  mutate(region = geo_name)
female1$region <- tolower(female1$geo_name)
female1 <- female1 %>% 
  select(region, unemp, type)

# I first combined the female and male graduation rates tables into a new tibble
# called "both." Then I joined "both" with the states data to get "combo."
both1 <- rbind(female1, male1)
combo1 <- left_join(states, both1, by = "region") %>% 
  select(long, lat, order, group, region, unemp, type)
```


```{r combined_sex}
combo_sex <- combo %>% full_join(combo1, by = c("long", "lat", "group", "order", "region", "type")) %>% 
  rename("School Dropout Rate" = "drop_rate", "Unemployment Rate" = "unemp") %>%
  pivot_longer(cols = c("School Dropout Rate", "Unemployment Rate"), names_to = "datatype", values_to = "count") %>% 
  mutate_if(is.numeric, ~round(., 1))

ggplot(combo_sex, aes(x = long, y = lat, group = group, fill = count, frame = datatype)) +
  geom_polygon(color = "white") +
  coord_fixed(1.3) +
  labs(title = "A Comparison of the School Dropout Rate and the Unemployment Rate \n By Sex in 2017",
       subtitle = "{current_frame}",
       caption = "Source: American Community Survey 2017",
       fill = "{current_frame}") +
  scale_fill_viridis(option = "magma", 
                     direction = -1,
                     guide = guide_colorbar(direction = "horizontal",
                                            barheight = unit(2, units = "mm"),
                                            barwidth = unit(35, units = "mm"),
                                            draw.ulim = FALSE,
                                            title.position = "top",
                                            title.hjust = 0.5,
                                            label.hjust = 0.5),
                     breaks = c(2, 4, 6, 8),
                     labels = c("2%", "4%", "6%", "8%")) +
  facet_wrap(~ type) +
  theme_void() +
  theme(legend.position = "bottom",
        legend.spacing.x = unit(1, 'cm'),
        plot.title = element_text(size = 13),
        plot.subtitle = element_text(size = 10)) +
  transition_manual(datatype)

anim_save("combined_sex.gif", animation = last_animation(), path = "final_project", width = 1400, height = 700)
```


```{r drop_race}

# I removed the first row since it shows the graduation rate for the entire
# nation, not the states. I then created a new column, region, which transformed
# all the states' names into lowercase letters, which will facilitate combining
# it with the states data. Next, I made four individual tibbles for the four
# different races. For each of these tibbles, I created a new variable, race,
# which will help me facet them later on. I also renamed all of their
# percentages into a common variable, pct, so that I can combine them.

race_grad <- nces2017[-1,]
race_grad$region <- tolower(race_grad$"1")
# combined_race <- left_join(states, race_grad, by = "region")

white1 <- race_grad %>% 
  mutate(race = "White", pct = race_grad$"9") %>% 
  select(region, race, pct) %>% 
  mutate(drop_rate = 100 - pct)

black1 <- race_grad %>% 
  mutate(race = "Black", pct = race_grad$"10") %>% 
  select(region, race, pct) %>% 
  mutate(drop_rate = 100 - pct)

hispanic1 <- race_grad %>% 
  mutate(race = "Hispanic", pct = race_grad$"11") %>% 
  select(region, race, pct) %>% 
  mutate(drop_rate = 100 - pct)

asian1 <- race_grad %>% 
  mutate(race = "Asian", pct = race_grad$"12") %>% 
  select(region, race, pct) %>% 
  mutate(drop_rate = 100 - pct)

combined1 <- rbind(white1, black1, hispanic1, asian1)
combined_grad_race <- left_join(states, combined1, by = "region")
combined_grad_race$race <- tolower(combined_grad_race$race)
```


```{r race_unemp}

# for whites
white <- unemp_data %>% 
  select(geo_name, 
         se_a17006a_001, 
         se_a17006a_003) %>% 
  mutate(unemp = (se_a17006a_003/se_a17006a_001)*100) %>% 
  mutate(race = "white") %>% 
  mutate(region = geo_name)

# I then turned all the states in the geo_name column into lowercase letters so
# that it would facilitate the left_join function that I would later use.
white$region <- tolower(white$geo_name)
white <- white %>% 
  select(region, unemp, race)

# for blacks
black <- unemp_data %>% 
  select(geo_name, 
         se_a17006b_001, 
         se_a17006b_003) %>% 
  mutate(unemp = (se_a17006b_003/se_a17006b_001)*100) %>% 
  mutate(race = "black") %>% 
  mutate(region = geo_name)
black$region <- tolower(black$geo_name)
black <- black %>% 
  select(region, unemp, race)

# asian
asian <- unemp_data %>% 
  select(geo_name, 
         se_a17006d_001, 
         se_a17006d_003) %>% 
  mutate(unemp = (se_a17006d_003/se_a17006d_001)*100) %>% 
  mutate(race = "asian") %>% 
  mutate(region = geo_name)
asian$region <- tolower(asian$geo_name)
asian <- asian %>% 
  select(region, unemp, race)

# hispanic
hispanic <- unemp_data %>% 
  select(geo_name, 
         se_a17006h_001, 
         se_a17006h_003) %>% 
  mutate(unemp = (se_a17006h_003/se_a17006h_001)*100) %>% 
  mutate(race = "hispanic") %>% 
  mutate(region = geo_name)
hispanic$region <- tolower(hispanic$geo_name)
hispanic <- hispanic %>% 
  select(region, unemp, race)

# I first combined the race unemployment rates tables into a new tibble called
# "both." Then I joined "both" with the states data to get "combined_unemp_race"
all_race <- rbind(white, black, asian, hispanic)
combined_unemp_race <- left_join(states, all_race, by = "region")
```


```{r combined_race}

# function to capitalize only the first letter of a word
capFirst <- function(s) {
    paste(toupper(substring(s, 1, 1)), substring(s, 2), sep = "")
}

combined_race <- combined_grad_race %>%
  full_join(combined_unemp_race, 
            by = c("long", "lat", "group", "order", "region", "subregion", "race")) %>% 
  rename("School Dropout Rate" = "drop_rate", "Unemployment Rate" = "unemp") %>%
  pivot_longer(cols = c("School Dropout Rate", "Unemployment Rate"), names_to = "datatype", values_to = "count") %>% 
  mutate_if(is.numeric, ~round(., 1))

combined_race$race <- capFirst(combined_race$race)

ggplot(combined_race, aes(x = long, y = lat, group = group, fill = count, frame = datatype)) +
  geom_polygon(color = "white") +
  coord_fixed(1.3) +
  labs(title = "A Comparison of the School Dropout Rate and the Unemployment Rate \n By Race in 2017",
       subtitle = "{current_frame}",
       caption = "Source: American Community Survey 2017",
       fill = "{current_frame}") +
  scale_fill_viridis(option = "viridis", 
                     direction = -1,
                     guide = guide_colorbar(direction = "horizontal",
                                            barheight = unit(2, units = "mm"),
                                            barwidth = unit(35, units = "mm"),
                                            draw.ulim = FALSE,
                                            title.position = "top",
                                            title.hjust = 0.5,
                                            label.hjust = 0.5),
                     breaks = c(10, 20, 30),
                     labels = c("10%", "20%", "30%")) +
  facet_wrap(~ race) +
  theme_void() +
  theme(legend.position = "bottom", 
        plot.title = element_text(size = 13),
        plot.subtitle = element_text(size = 10)) +
  transition_manual(datatype)

anim_save("combined_race.gif", animation = last_animation(), path = "final_project", width = 1400, height = 700)
```


```{r poverty_status_sex}
# new code
both <- both %>% select(region, drop_rate, type)
joined_sex <- both1 %>% left_join(both, by = c("region", "type"))

ggplot(joined_sex, aes(x = unemp, y = drop_rate, color = type)) +
  geom_point() +
  geom_smooth(method = "lm", se = F) +
  labs(title = "Relationship Between Unemployment Rate and School Dropout Rate \n Based on Sex in 2017",
       color = "Sex",
       x = "Unemployment Rate",
       y = "School Dropout Rate \n (For Population 16-19 Years)",
       caption = "Source: American Community Survey 2017 and National Center for Education Statistics 2017") +
  scale_x_continuous(breaks = seq(2, 10, 1), limits = c(2, 10), 
                     labels = c("2%", "3%", "4%", "5%", "6%", "7%", "8%", "9%", "10%")) +
  scale_y_continuous(breaks = c(2, 3, 4, 5, 6, 7), labels = c("2%", "3%", "4%", "5%", "6%", "7%")) +
  scale_color_manual(values = c("deeppink", "deepskyblue"), 
                     labels = c("Female", "Male")) +
  theme_classic()

# old code
pov_status_sex <- pov_status %>% 
  mutate(male = (se_a13005_003/se_a13005_001) * 100) %>% 
  mutate(female = (se_a13005_004/se_a13005_001) * 100)

# started with females

female1 <- female
female1$geo_name = tolower(female1$geo_name)

pov_status_female <- left_join(pov_status_sex, female1, by = "geo_name") %>% 
  mutate(drop_rate = (se_a12003b_002/se_a12003b_001)*100) %>% 
  select(geo_name, female, drop_rate)

# males
male1 <- male
male1$geo_name = tolower(male1$geo_name)

pov_status_male <- left_join(pov_status_sex, male1, by = "geo_name") %>% 
  mutate(drop_rate = (se_a12003a_002/se_a12003a_001)*100) %>% 
  select(geo_name, male, drop_rate)

pov_status_sex_plot <- ggplot() +
  geom_point(data = pov_status_male, aes(x = male, y = drop_rate), col = "blue", alpha = 0.8) +
  geom_smooth(data = pov_status_male, aes(x = male, y = drop_rate), method = "lm", se = F, col = "blue", alpha = 0.8) +
  geom_point(data = pov_status_female, aes(x = female, y = drop_rate), col = "deeppink2", alpha = 0.8) +
  geom_smooth(data = pov_status_female, aes(x = female, y = drop_rate), method = "lm", se = F, col = "deeppink2", alpha = 0.8) +
  scale_x_continuous(breaks = seq(3, 13, 1), limits = c(3, 13)) +
  labs(title = "Relationship Between Poverty Status and School Dropout Rate \n Based on Sex in 2017",
       x = "Unemployment Rate",
       y = "School Dropout Rate",
       caption = "Source: American Community Survey 2017 and National Center for Education Statistics 2017") +
  annotate("text", x = 12.1, y = 3.5, label = "Sex", color = "black", size = 5) +
  annotate("text", x = 12.4, y = 3.1, label = "Male", color = "black", size = 4) +
  annotate("text", x = 12.5, y = 2.7, label = "Female", color = "black", size = 4) +
  geom_segment(aes(x = 11.7, y = 3.1, xend = 12, yend = 3.1), col = "blue", data = pov_status_male) +
  geom_segment(aes(x = 11.7, y = 2.7, xend = 12, yend = 2.7), col = "deeppink2", data = pov_status_female) +
  theme_classic()
```


```{r poverty_status_race}
# new code
combined_unemp_race <- combined_unemp_race
combined_unemp_race_reduced <- unique( combined_unemp_race[ , 1:3 ] )
combined_final1 <- combined_final1 %>% 
  select(geo_name, drop_rate, race)
combined_final1_reduced <- unique( combined_final1[ , 1:3 ] )
combined_new <- left_join(combined_unemp_race_reduced, combined_final1_reduced, 
                          by = c("geo_name","race"))

ggplot(combined_new, aes(x = unemp, y = drop_rate, color = race)) +
  geom_point() +
  geom_smooth(method = "lm", se = F) +
  labs(title = "Relationship Between Unemployment Rate and School Dropout Rate \n Based on Race in 2017",
       color = "Race",
       x = "Unemployment Rate",
       y = "School Dropout Rate \n (For Population 16-19 Years)",
       caption = "Source: American Community Survey 2017 and National Center for Education Statistics 2017") +
  scale_x_continuous(breaks = c(5, 10, 15), labels = c("5%", "10%", "15%")) +
  scale_y_continuous(breaks = c(10, 20, 30), labels = c("10%", "20%", "30%")) +
  scale_color_manual(values = c("goldenrod2", "darkolivegreen", "deeppink2", "midnightblue"), 
                     labels = c("Asian", "Black", "Hispanic", "White")) +
  theme_classic()

# old code
pov_status_race <- pov_status %>% 
  mutate(white = (se_a13001a_002/se_a13001a_001) * 100) %>% 
  mutate(black = (se_a13001b_002/se_a13001b_001) * 100) %>% 
  mutate(asian = (se_a13001d_002/se_a13001d_001) * 100) %>% 
  mutate(hispanic = (se_a13001h_002/se_a13001h_001) * 100)

combined_final1 <- combined_final %>% 
  mutate(geo_name = region) %>% 
  mutate(drop_rate = 100 - pct)

pov_status_joined <- left_join(pov_status_race, combined_final1, by = "geo_name") %>% 
  select(geo_name, white, black, asian, hispanic, drop_rate, race)

statenames <- unique(pov_status_joined$geo_name)

pov_status_final <- vector()
for(i in 1:length(statenames)){
  sub <- unique(pov_status_joined[pov_status_joined$geo_name == statenames[i], ])
  addition <- c(snames[i], unlist(sub[1, 2:5]), sub$drop_rate[c(1, 2, 4, 3)])
  pov_status_final <- rbind(pov_status_final, addition)
}
pov_status_final <- as.data.frame(pov_status_final)
colnames(pov_status_final) <- c('state', 'whitepov', 'blackpov', 'asianpov', 'hisppov',
                       'whitedo', 'blackdo', 'asiando', 'hispdo')
pov_status_final[, -1] <- apply(pov_status_final[, -1], 2, as.numeric)
pov_status_final <- 
  pov_status_final %>% na.omit()
pov_status_final1 <- pov_status_final
pov_status_final2 <- pov_status_final
pov_status_final3 <- pov_status_final

pov_plot <- ggplot() +
  geom_point(data = pov_status_final, aes(x = whitepov, y = whitedo), col = "darkolivegreen", alpha = 0.8) +
  geom_smooth(data = pov_status_final, aes(x = whitepov, y = whitedo), method = "lm", se = F, col = "darkolivegreen", alpha = 0.8) +
  geom_point(data = pov_status_final1, aes(x = blackpov, y = blackdo), col = "deeppink2", alpha = 0.8) +
  geom_smooth(data = pov_status_final1, aes(x = blackpov, y = blackdo), method = "lm", se = F, col = "deeppink2", alpha = 0.8) +
  geom_point(data = pov_status_final2, aes(x = asianpov, y = asiando), col = "goldenrod2", alpha = 0.8) +
  geom_smooth(data = pov_status_final2, aes(x = asianpov, y = asiando), method = "lm", se = F, col = "goldenrod2", alpha = 0.8) +
  geom_point(data = pov_status_final3, aes(x = hisppov, y = hispdo), col = "midnightblue", alpha = 0.8) +
  geom_smooth(data = pov_status_final3, aes(x = hisppov, y = hispdo), method = "lm", se = F, col = "midnightblue", alpha = 0.8) +
  scale_x_continuous(breaks = seq(5, 45, 5), limits = c(5, 45)) +
  scale_y_continuous(breaks = seq(0, 35, 5), limits = c(0, 35)) +
  labs(title = "Relationship Between Poverty Status and School Dropout Rate \n Based on Race in 2017",
       x = "Percentage Whose Income is Below Poverty Level",
       y = "School Dropout Rate",
       caption = "Source: American Community Survey 2017 and National Center for Education Statistics 2017") +
  annotate("text", x = 40, y = 15, label = "Race", color = "black", size = 6) +
  annotate("text", x = 41, y = 12, label = "White", color = "black", size = 5.5) +
  annotate("text", x = 41, y = 10, label = "Black", color = "black", size = 5.5) +
  annotate("text", x = 41, y = 8, label = "Asian", color = "black", size = 5.5) +
  annotate("text", x = 41.3, y = 6, label = "Hispanic", color = "black", size = 5.5) +
  geom_segment(aes(x = 37.5, y = 12, xend = 39, yend = 12), col = "darkolivegreen", data = pov_status_final) +
  geom_segment(aes(x = 37.5, y = 10, xend = 39, yend = 10), col = "deeppink2", data = pov_status_final) +
  geom_segment(aes(x = 37.5, y = 8, xend = 39, yend = 8), col = "goldenrod", data = pov_status_final) +
  geom_segment(aes(x = 37.5, y = 6, xend = 39, yend = 6), col = "midnightblue", data = pov_status_final) +
  theme_classic()
```


```{r}
 dropout_county_male <- county_data %>% 
            select(region, subregion, se_a12003a_001, se_a12003a_002) %>% 
            mutate(data = (se_a12003a_002/se_a12003a_001)*100) %>% 
            mutate(type = "male") %>% 
            mutate(datatype = "Dropout Rate") %>% 
            select(region, subregion, data, type, datatype)
        
        dropout_county_female <- county_data %>% 
            select(region, subregion, se_a12003b_001, se_a12003b_002) %>% 
            mutate(data = (se_a12003b_002/se_a12003b_001)*100) %>% 
            mutate(type = "female") %>% 
            mutate(datatype = "Dropout Rate") %>% 
            select(region, subregion, data, type, datatype)
        
        dropout_county_both <- rbind(dropout_county_male, dropout_county_female)
        
        unemp_county_male <- county_data %>% 
            select(region, subregion, se_a17005a_001, se_a17005a_003) %>% 
            mutate(data = (se_a17005a_003/se_a17005a_001)*100) %>% 
            mutate(type = "male") %>% 
            mutate(datatype = "Unemployment Rate") %>% 
            select(region, subregion, data, type, datatype)
        
        unemp_county_female <- county_data %>% 
            select(region, subregion, se_a17005b_001, se_a17005b_003) %>% 
            mutate(data = (se_a17005b_003/se_a17005b_001)*100) %>% 
            mutate(type = "female") %>% 
            mutate(datatype = "Unemployment Rate") %>% 
            select(region, subregion, data, type, datatype)
        
        unemp_county_both <- rbind(unemp_county_male, unemp_county_female)
        county_all <- rbind(unemp_county_both, dropout_county_both)
        county_all_final <- left_join(county, county_all, by = c("region", "subregion"))
        
        county_all_final$type <- toupper(county_all_final$type)
        county_all_final$region <- toupper(county_all_final$region)
        
        county_all_final %>% 
            filter(region == "NEW YORK") %>%
            filter(datatype == "Dropout Rate") %>% 
            ggplot(aes(x = long, y = lat, group = group, fill = data)) +
            geom_polygon(color = "white") +
          facet_wrap(~ type) +
            labs(title = paste("| Map of by Sex in 2017"),
                 subtitle = paste("County Level Data"),
                 caption = "Source: American Community Survey 2017") +
            scale_fill_viridis(option = "magma", 
                               direction = -1,
                               guide = guide_colorbar(direction = "horizontal",
                                                      barheight = unit(2, units = "mm"),
                                                      barwidth = unit(35, units = "mm"),
                                                      draw.ulim = FALSE,
                                                      title.position = "top",
                                                      title.hjust = 0.5,
                                                      label.hjust = 0.5)) +
            theme(legend.position = "bottom",
                  legend.spacing.x = unit(1, 'cm')) +
            theme_void()
        
        dataset1 <- county_all_final %>% 
            filter(region == "NEW YORK") %>% 
            filter(datatype == "Dropout Rate") %>% 
            mutate(dropout1 = data) %>% 
          select(region, subregion, dropout1, type)
        
        dataset1_reduced <- unique( dataset1[ , 1:4 ] )
        
        dataset2 <- county_all_final %>% 
            filter(region == "NEW YORK") %>% 
            filter(datatype == "Unemployment Rate") %>% 
            mutate(unemp1 = data) %>% 
          select(region, subregion, unemp1, type)
        
        dataset2_reduced <- unique( dataset2[ , 1:4 ] )
        county_reg_joined <- dataset1_reduced %>% 
            left_join(dataset2_reduced, by = c("region", "subregion", "type"))
        
        county_reg_joined %>% 
            ggplot(aes(x = unemp1, y = dropout1, color = type)) +
            geom_point() +
            geom_smooth(method = "lm", se = F) +
            labs(title = paste("| Relationship between School Dropout Rate and Unemployment Rate by Sex in 2017"),
                 subtitle = paste("County Level Data"),
                 caption = "Source: American Community Survey 2017",
                 color = "Sex",
                 x = "Unemployment Rate",
                 y = "School Dropout Rate \n (For Population 16-19 Years)") +
          scale_x_continuous(breaks = c(2.5, 5.0, 7.5, 10.0, 12.5), 
                           labels = c("2.5%", "5.0%", "7.5%", "10.0%", "12.5%")) +
          scale_y_continuous(breaks = c(0, 10, 20, 30), 
                           labels = c("0%", "10%", "20%", "30%")) +
          scale_color_manual(values = c("deeppink", "deepskyblue")) +
          theme_classic()
```

